swagger: "2.0"
info:
  title: ONCHAIN.IO API overview
  version: v2
servers:
  - url: https://onchain.io
    description: Main production server


definitions:
  balance:
    type: object
    required:
      - usd_balance
      - satoshi_balance
    properties:
      usd_balance:
        type: integer
      satoshi_balance:
        type: integer
    
paths:
  /api/address/{coin}/{addresses}:
    get:
      tags:
        - Address API
      parameters:
        - in: path
          name: coin   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: The name of the coin i.e. bitcoin
        - in: path
          name: addresses   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: A comma seperated list of public addresses
      operationId: Get Balance
      summary: Get Balance
      description: Returns the satoshi balance, usd balance and user viewable balance for a set of addresses
      produces:
      - application/json
      responses:
        default:
          description: Returns the pets that were deleted
          schema:
            type: array
            items:
              $ref: "#/definitions/balance"
  /api/address/history/{coin}/{addresses}:
    get:
      tags:
        - Address API
      parameters:
        - in: path
          name: coin   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: The name of the coin i.e. bitcoin
        - in: path
          name: addresses   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: A comma seperated list of public addresses
      operationId: Get History
      summary: Get History
      description: Returns the transaction history for an address or addresses.
      produces:
      - application/json
      responses:
        default:
          description: Returns the pets that were deleted
          schema:
            type: array
            items:
              $ref: "#/definitions/balance"
  /api/address/utxo/{coin}/{addresses}:
    get:
      tags:
        - Address API
      parameters:
        - in: path
          name: coin   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: The name of the coin i.e. bitcoin
        - in: path
          name: addresses   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: A comma seperated list of public addresses
      operationId: Get Unspent
      summary: Get Unspent Outs
      description: Returns the unspent outputs for an address or addresses.
      produces:
      - application/json
      responses:
        default:
          description: Returns the pets that were deleted
          schema:
            type: array
            items:
              $ref: "#/definitions/balance"
  /api/transaction/send/{coin}/{rawtx}:
    post:
      tags:
        - Address API
      parameters:
        - in: path
          name: coin   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: The name of the coin i.e. bitcoin
        - in: path
          name: rawtx   
          required: true
          schema:
            type: string
          description: The raw signed transaction as a hex string
      operationId: Send TX
      summary: Send Transaction
      description: Send a transaction onto the network.
      produces:
      - application/json
      responses:
        default:
          description: Returns the pets that were deleted
          schema:
            type: array
            items:
              $ref: "#/definitions/balance"
consumes:
- application/json